[build]
builder = "NIXPACKS"
buildCommand = "mvn -DskipTests clean package"

[deploy]
startCommand = "java -jar target/position-management-1.0.0.jar"
healthcheckPath = "/webapi/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
